// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace API.Models;

public partial class Person
{
    [Key]
    public int Id { get; set; }

    public required string FirstName { get; set; }

    public required string LastName { get; set; }

    public string MiddleName { get; set; } = String.Empty;

    public required string PhoneNumber { get; set; }

    public string Email { get; set; } = String.Empty;
}