// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Reflection.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Configuration;

namespace API.Models;

public partial class ServiceSchedulerContext : DbContext
{
    public ServiceSchedulerContext(DbContextOptions<ServiceSchedulerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> Persons { get; set; }
    public virtual DbSet<Customer> Customers{ get; set; }

    public virtual DbSet<Skill> Skills { get; set; }


}